normal=$'\e[0m'

bold=$'\e[1m'
dimmed=$'\e[2m'
italic=$'\e[3m'
underlined=$'\e[4m'
flashing=$'\e[5m'
xchg_bg_fg=$'\e[7m'
transparent=$'\e[8m'
strikethrough=$'\e[9m'

dark=$'\e[30m'
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
blue=$'\e[34m'
pink=$'\e[35m'
lime=$'\e[36m'
light=$'\e[37m'

dark_bg=$'\e[40m'
red_bg=$'\e[41m'
green_bg=$'\e[42m'
yellow_bg=$'\e[43m'
blue_bg=$'\e[44m'
pink_bg=$'\e[45m'
lime_bg=$'\e[46m'
light_bg=$'\e[47m'
