name: Feature Request
description: Request a Feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking your time!
  - type: textarea
    attributes:
      label: Description
      description: Short Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Explanation
      description: Detailed Explanation (if required any)
    validations:
      required: false
