#!/bin/python
'''Variable Definitions'''
TempDir = '/tmp/gdm-settings'
TempShellDir = f'{TempDir}/gnome-shell'
ThemesDir = '/usr/share/themes'
GnomeShellDir = '/usr/share/gnome-shell'
GdmGresourceFile = f'{GnomeShellDir}/gnome-shell-theme.gresource'
UbuntuGdmGresourceFile = f'{GnomeShellDir}/gdm3-theme.gresource'
GdmGresourceManualBackup = f'{GdmGresourceFile}.bak'
GdmGresourceAutoBackup = f'{GdmGresourceFile}.default'
GdmBackground = f'{GnomeShellDir}/theme/gdm-background'
ConfigDir = '/etc/gdm-settings'
CurrentBackgroundFile = f'{ConfigDir}/currentBackground'
CurrentThemeFile = f'{ConfigDir}/currentTheme'
CustomCss = f'{ConfigDir}/custom.css'
GresourceBasename = 'gnome-shell-theme.gresource'
CustomThemeIdentity = 'custom-theme'
AcceptableColors = ['black'
                    ,'silver'
                    ,'gray'
                    ,'white'
                    ,'maroon'
                    ,'red'
                    ,'purple'
                    ,'fuchsia'
                    ,'green'
                    ,'lime'
                    ,'olive'
                    ,'yellow'
                    ,'navy'
                    ,'blue'
                    ,'teal'
                    ,'aqua'
                         
                    ,'aliceblue'
                    ,'antiquewhite'
                    ,'aqua'
                    ,'aquamarine'
                    ,'azure'
                    ,'beige'
                    ,'bisque'
                    ,'black'
                    ,'blanchedalmond'
                    ,'blue'
                    ,'blueviolet'
                    ,'brown'
                    ,'burlywood'
                    ,'cadetblue'
                    ,'chartreuse'
                    ,'chocolate'
                    ,'coral'
                    ,'cornflowerblue'
                    ,'cornsilk'
                    ,'crimson'
                    ,'cyan'
                    ,'darkblue'
                    ,'darkcyan'
                    ,'darkgoldenrod'
                    ,'darkgray'
                    ,'darkgreen'
                    ,'darkgrey'
                    ,'darkkhaki'
                    ,'darkmagenta'
                    ,'darkolivegreen'
                    ,'darkorange'
                    ,'darkorchid'
                    ,'darkred'
                    ,'darksalmon'
                    ,'darkseagreen'
                    ,'darkslateblue'
                    ,'darkslategray'
                    ,'darkslategrey'
                    ,'darkturquoise'
                    ,'darkviolet'
                    ,'deeppink'
                    ,'deepskyblue'
                    ,'dimgray'
                    ,'dimgrey'
                    ,'dodgerblue'
                    ,'firebrick'
                    ,'floralwhite'
                    ,'forestgreen'
                    ,'fuchsia'
                    ,'gainsboro'
                    ,'ghostwhite'
                    ,'gold'
                    ,'goldenrod'
                    ,'gray'
                    ,'green'
                    ,'greenyellow'
                    ,'grey'
                    ,'honeydew'
                    ,'hotpink'
                    ,'indianred'
                    ,'indigo'
                    ,'ivory'
                    ,'khaki'
                    ,'lavender'
                    ,'lavenderblush'
                    ,'lawngreen'
                    ,'lemonchiffon'
                    ,'lightblue'
                    ,'lightcoral'
                    ,'lightcyan'
                    ,'lightgoldenrodyellow'
                    ,'lightgray'
                    ,'lightgreen'
                    ,'lightgrey'
                    ,'lightpink'
                    ,'lightsalmon'
                    ,'lightseagreen'
                    ,'lightskyblue'
                    ,'lightslategray'
                    ,'lightslategrey'
                    ,'lightsteelblue'
                    ,'lightyellow'
                    ,'lime'
                    ,'limegreen'
                    ,'linen'
                    ,'magenta'
                    ,'maroon'
                    ,'mediumaquamarine'
                    ,'mediumblue'
                    ,'mediumorchid'
                    ,'mediumpurple'
                    ,'mediumseagreen'
                    ,'mediumslateblue'
                    ,'mediumspringgreen'
                    ,'mediumturquoise'
                    ,'mediumvioletred'
                    ,'midnightblue'
                    ,'mintcream'
                    ,'mistyrose'
                    ,'moccasin'
                    ,'navajowhite'
                    ,'navy'
                    ,'oldlace'
                    ,'olive'
                    ,'olivedrab'
                    ,'orange'
                    ,'orangered'
                    ,'orchid'
                    ,'palegoldenrod'
                    ,'palegreen'
                    ,'paleturquoise'
                    ,'palevioletred'
                    ,'papayawhip'
                    ,'peachpuff'
                    ,'peru'
                    ,'pink'
                    ,'plum'
                    ,'powderblue'
                    ,'purple'
                    ,'red'
                    ,'rosybrown'
                    ,'royalblue'
                    ,'saddlebrown'
                    ,'salmon'
                    ,'sandybrown'
                    ,'seagreen'
                    ,'seashell'
                    ,'sienna'
                    ,'silver'
                    ,'skyblue'
                    ,'slateblue'
                    ,'slategray'
                    ,'slategrey'
                    ,'snow'
                    ,'springgreen'
                    ,'steelblue'
                    ,'tan'
                    ,'teal'
                    ,'thistle'
                    ,'tomato'
                    ,'turquoise'
                    ,'violet'
                    ,'wheat'
                    ,'white'
                    ,'whitesmoke'
                    ,'yellow'
                    ,'yellowgreen'
]